### ISSUE TITLE
GSon error

### ISSUE THREAD

**Issue by punkeel** [aumgn/DACv2#9]
2013-06-26 23:59:09 [SEVERE] Could not load 'plugins/dac2-0.8.0 (1).jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/google/gson/TypeAdapterFactory
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:184)
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:305)
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:230)
    at org.bukkit.craftbukkit.v1_5_R3.CraftServer.loadPlugins(CraftServer.java:241)
    at org.bukkit.craftbukkit.v1_5_R3.CraftServer.reload(CraftServer.java:605)
    at org.bukkit.Bukkit.reload(Bukkit.java:275)
    at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:23)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:189)
    at org.bukkit.craftbukkit.v1_5_R3.CraftServer.dispatchCommand(CraftServer.java:525)
    at org.bukkit.craftbukkit.v1_5_R3.CraftServer.dispatchServerCommand(CraftServer.java:514)
    at net.minecraft.server.v1_5_R3.DedicatedServer.an(DedicatedServer.java:262)
    at net.minecraft.server.v1_5_R3.DedicatedServer.r(DedicatedServer.java:227)
    at net.minecraft.server.v1_5_R3.MinecraftServer.q(MinecraftServer.java:477)
    at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:410)
    at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)
**Caused by: java.lang.NoClassDefFoundError: com/google/gson/TypeAdapterFactory**
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:266)
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:173)
    ... 14 more
Caused by: java.lang.ClassNotFoundException: com.google.gson.TypeAdapterFactory
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at org.bukkit.plugin.java.PluginClassLoader.findClass0(PluginClassLoader.java:80)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:53)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
    ... 17 more

File : https://github.com/aumgn/DACv2/blob/7a517fd9fde362c92db4ce36d68bb8f8c4429a9e/src/main/java/fr/aumgn/dac2/arena/regions/GsonRegionFactory.java

**Comment by aumgn** [comment]
Tu as installe BukkitUtils ? C'est elle qui integre Gson.
Je ne suis pas sur de voir ou le fichier GsonRegionFactory entre en jeu ?

**Comment by punkeel** [comment]
Mise à jour dépendance CB et non utilisation du standalone. Erreur de ma part, mais "sans compter le standalone" je trouvais intéressant de créer une issue, au cas où d'autres aient besoin de ça :)
